project_id = "jnkwooocjpgpznittueo"

[functions.companies-house-lookup]
verify_jwt = false

[functions.process-document]
verify_jwt = false

[functions.bulk-epc-enrich]
verify_jwt = false

[functions.bulk-price-paid-enrich]
verify_jwt = false
