// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // localStorage so sessions persist across tab closes and are shared between tabs.
    // Previous config used sessionStorage + persistSession which contradicted each other
    // and caused users to be logged out on every new tab/window.
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Loosely-typed handle for tables/RPCs not yet in the generated Database types,
// or queries whose column shape can't be inferred. Prefer `supabase` where
// types are available; reach for this only when you'd otherwise write
// `(supabase as any)`.
 
export const supabaseAny: any = supabase;